/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./src/components/Button/Button.vue')['default']
    Circle: typeof import('./src/components/Button/demo/circle.vue')['default']
    DadaButton: typeof import('@/components/Button/Button.vue')['default']
    DadaInput: typeof import('@/components/Input/Input.vue')['default']
    DadaRadio: typeof import('@/components/Radio/Radio.vue')['default']
    Input: typeof import('./src/components/Input/Input.vue')['default']
    InputBase: typeof import('./src/components/Input/demo/inputBase.vue')['default']
    InputDemo: typeof import('./src/components/Input/demo/inputDemo.vue')['default']
    InputForm: typeof import('./src/components/Input/demo/inputForm.vue')['default']
    InputSearch: typeof import('./src/components/Input/demo/inputSearch.vue')['default']
    Radio: typeof import('./src/components/Radio/Radio.vue')['default']
    RadioDefault: typeof import('./src/components/Radio/demo/radioDefault.vue')['default']
    Size: typeof import('./src/components/Button/demo/size.vue')['default']
    Text: typeof import('./src/components/Button/demo/text.vue')['default']
    Type: typeof import('./src/components/Button/demo/type.vue')['default']
  }
}
