/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./src/components/Button/Button.vue')['default']
    Circle: typeof import('./src/components/Button/demo/circle.vue')['default']
    DadaButton: typeof import('@/components/Button/Button.vue')['default']
    DadaDatePicker: typeof import('@/components/DatePicker/DatePicker.vue')['default']
    DadaInput: typeof import('@/components/Input/Input.vue')['default']
    DadaRadio: typeof import('@/components/Radio/Radio.vue')['default']
    DadaSelect: typeof import('@/components/Select/Select.vue')['default']
    DadaTabs: typeof import('@/components/Tabs/Tabs.vue')['default']
    DadaTimePicker: typeof import('@/components/TimePicker/TimePicker.vue')['default']
    DatePicker: typeof import('./src/components/DatePicker/DatePicker.vue')['default']
    DatePickerDefault: typeof import('./src/components/DatePicker/demo/DatePickerDefault.vue')['default']
    DatePickerFields: typeof import('./src/components/DatePicker/demo/DatePickerFields.vue')['default']
    Input: typeof import('./src/components/Input/Input.vue')['default']
    InputBase: typeof import('./src/components/Input/demo/inputBase.vue')['default']
    InputDemo: typeof import('./src/components/Input/demo/inputDemo.vue')['default']
    InputForm: typeof import('./src/components/Input/demo/inputForm.vue')['default']
    InputSearch: typeof import('./src/components/Input/demo/inputSearch.vue')['default']
    Radio: typeof import('./src/components/Radio/Radio.vue')['default']
    RadioDefault: typeof import('./src/components/Radio/demo/radioDefault.vue')['default']
    RadioMuti: typeof import('./src/components/Radio/demo/radioMuti.vue')['default']
    Select: typeof import('./src/components/Select/Select.vue')['default']
    SelectDefault: typeof import('./src/components/Select/demo/SelectDefault.vue')['default']
    Size: typeof import('./src/components/Button/demo/size.vue')['default']
    Tabs: typeof import('./src/components/Tabs/Tabs.vue')['default']
    TabsDemo: typeof import('./src/components/Tabs/demo/tabsDemo.vue')['default']
    TabsType: typeof import('./src/components/Tabs/demo/tabsType.vue')['default']
    Text: typeof import('./src/components/Button/demo/text.vue')['default']
    TimePicker: typeof import('./src/components/TimePicker/TimePicker.vue')['default']
    TimePickerDefault: typeof import('./src/components/TimePicker/demo/TimePickerDefault.vue')['default']
    Type: typeof import('./src/components/Button/demo/type.vue')['default']
  }
}
